version: "3.9"

networks:
  todolist:

services:
  front:
    image: marcpartensky/je-todoapp-react
    restart: unless-stopped
    build:
      context: ./react
      dockerfile: ./react/Dockerfile
    environment:
      HOST: 0.0.0.0
      PORT: 80
      SPRING_API_URL: http://localhost:8080 # not suitable for production
    ports:
      - "3000:80"

  back:
    image: marcpartensky/je-todoapp-spring-api
    restart: unless-stopped
    build:
      context: ./spring-api
      dockerfile: ./spring-api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: todoapp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - todolist

  postgres:
    image: postgres:14
    restart: unless-stopped
    # ports:
    #   - "5432:5432"
    volumes:
      - ./volumes/postgres/dump:/srv/postgresql/dump
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - todolist
