package com.example.accessingdatamysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/todo")
public class MainController {
 // Which is auto-generated by Spring, we will use it to handle the data
  @Autowired
  private TodoRepository todoRepository;

  @PostMapping(path="/add")
  public @ResponseBody String addTodo (
		@RequestParam String content,
		@RequestParam Boolean done
		) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request
    Todo todo = new Todo();
		todo.content = content;
		todo.done = done;
    todoRepository.save(todo);
    return "Saved";
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<Todo> getAllTodos() {
    // This returns a JSON or XML with the users
    return todoRepository.findAll();
  }
}
